### ISSUE TITLE
docker elasticsearch NetworkClient timeout

### ISSUE THREAD

**Issue by xuebkgithub** [openzipkin/docker-zipkin-dependencies#16]
docker yml
```ymal
  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=172.17.0.73
```

![image](https://user-images.githubusercontent.com/41730586/64692790-7e5bbd80-d4c8-11e9-9fa2-792472f6046c.png)

![image](https://user-images.githubusercontent.com/41730586/64692831-916e8d80-d4c8-11e9-8a00-a2978c84f8c0.png)

在 docker 里面启

**Comment by liunancun** [comment]
@xuebkgithub Is your problem solved?

**Comment by xuebkgithub** [comment]
yes
